site_name: Blog - CloudCollabDevTech
site_url: https://blog.cloudcollabdevtech.com
site_description: This website will contain information pertaining to all aspects of Cloud, Collaboration, Development and Technology in general.
use_directory_urls: false
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.svg
  features:
  - navigation.tabs
  - navigation.sections
  - toc.integrate
  - navigation.top
  - navigation.instant
  - navigation.instant.prefetch
  - navigation.instant.progress
  - navigation.tracking
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.sections
  - navigation.expand
  - navigation.path
  - search.suggest
  - search.highlight
  - toc.follow
  - toc.integrate
  - content.tabs.link
  - content.code.annotation
  - content.code.copy
  language: en
  icon:
    repo: fontawesome/brands/github
  palette:
  - scheme: default
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
    primary: navy
    accent: purple
  - scheme: slate
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode
    primary: teal
    accent: lime


markdown_extensions:
- pymdownx.highlight:
    anchor_linenums: true
- pymdownx.inlinehilite
- pymdownx.snippets
- admonition
- pymdownx.arithmatex:
    generic: true
- footnotes
- pymdownx.details
- pymdownx.superfences
- pymdownx.mark
- attr_list
- md_in_html
- pymdownx.critic
- pymdownx.caret
- pymdownx.keys
- pymdownx.mark
- pymdownx.tilde
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji
    emoji_generator: !!python/name:material.extensions.emoji.to_svg


plugins:
- awesome-pages
- search
- tags
- blog
- rss:
    match_path: blog/posts/.*
    date_from_meta:
      as_creation: date
    categories:
    - categories
    - tags
    comments_path: "#__comments"
# - section-index


extra:
  social:
  - icon: fontawesome/brands/github-alt
    link: https://github.com/cloudcollabdevtech
  - icon: fontawesome/brands/twitter
    link: https://twitter.com/cloudcollabdevtech
  - icon: fontawesome/brands/linkedin
    link: https://www.linkedin.com/in/cloudcollabdevtech
  consent:
    title: Cookie consent
    description: >-
      We use cookies to recognize your repeated visits and preferences, as well as to measure the effectiveness of our blogs and whether users find what they're searching for. With your consent, you're helping us to make our blogs better.
    actions:
    - accept
    - manage

nav:
- Blog:
  - blog/index.md
- Introduction: index.md
- Sandbox: domino.md

# Repository
repo_url: https://github.com/cloudcollabdevtech/bloganddocs
repo_name: CloudCollabDevTech/BlogandDocs

copyright: >
  <p> Copyright &copy; 2023 <a href="https://github.com/cloudcollabdevtech"  target="_blank" rel="noopener">Rishab Sharma</a> <br/> <a href="#__consent">Change cookie settings</a> </p>
